### ISSUE TITLE
Criar dataset com os dados de rankings

### ISSUE THREAD

**Issue by henryzord** [COPLIN-UFSM/rankings#4]
@diego-brenner-reis , @NathaleCK e @flrivas :

* [x] Criar um dataset no Power BI com as views do diagrama abaixo. As views estão disponíveis no banco bee
* [x] (Opcional, mas muito bem vindo) Incorporar novas informações à view de Universidades (descrição abaixo)

Existem algumas informações também que seria interessante adicionar à view R_V_UNIVERSIDADES_DIMENSAO, como por exemplo se uma universidade é gaúcha, brasileira, latina, ou do BRIC. Isso viraria uma coluna na view, onde 0 denotaria que a universidade não pertence àquele grupo, e 1 o contrário. Seria criada uma nova coluna para cada grupo (E_GAUCHA, E_BRASILEIRA, E_LATINA, E_BRIC, etc). 

O desenho das tabelas que são usadas para construir as views está [aqui](https://github.com/COPLIN-UFSM/rankings/blob/main/app/database_scripts/SCHEMA.md). **Não mexer nestas tabelas, pois uma aplicação Web depende delas do jeito como estão estruturadas.**

O script que gera as views está [aqui](https://github.com/COPLIN-UFSM/rankings/blob/main/app/database_scripts/ibmdb_views.sql). 

```mermaid
classDiagram
    R_V_PILARES_VALORES_FATO <|-- R_V_RANKINGS_DIMENSAO
    R_V_PILARES_VALORES_FATO <|-- R_V_UNIVERSIDADES_DIMENSAO

    class R_V_RANKINGS_DIMENSAO {
       ID_RANKING
       ID_PILAR
       NOME_RANKING
       NOME_PILAR_INGLES
       NOME_PILAR_PORTUGUES,
       DESCRICAO_PILAR_INGLES
       DESCRICAO_PILAR_PORTUGUES
    }

    class R_V_UNIVERSIDADES_DIMENSAO {
      ID_UNIVERSIDADE
      NOME_UNIVERSIDADE_INGLES
      NOME_UNIVERSIDADE_PORTUGUES
      ID_PAIS
      NOME_PAIS_PORTUGUES
      NOME_PAIS_INGLES
      ID_CONTINENTE
      NOME_CONTINENTE_INGLES
      NOME_CONTINENTE_PORTUGUES
    }

    class R_V_PILARES_VALORES_FATO {
      ID_UNIVERSIDADE
      ID_PILAR
      ANO
      VALOR_INICIAL
      VALOR_FINAL
    }
```

_(PS: tarefa dada pelo @marcelotuco - eu só documentei a demanda)_

**Comment by henryzord** [comment]
Ano de coleta de dados dos rankings: https://github.com/COPLIN-UFSM/rankings-data

**Comment by NathaleCK** [comment]
Dataset e relatório dos rankings criados no BI
