### ISSUE TITLE
Lista em Excel das universidades que estão nos rankings 

### ISSUE THREAD

**Issue by flrivas** [COPLIN-UFSM/rankings#8]
Lista filtrada das universidades que estão presentes nos rankings com foco nas universidades brasileiras.
O que foi feito:
- eliminação dos nomes duplicados;
- correção dos nomes (alguns estavam com grafia errada ou acentuação errada ou em inglês ou inglês misturado com português);
- filtragem das universidades do Rio Grande do Sul. A princípio achei 22, mas pode ter mais alguma na lista;
- separação do nome da universidade e sigla.
@henryzord 
@marcelotuco 
@diego-brenner-reis 
@NathaleCK 
[lista_universidades_brasileiras.xlsx](https://github.com/COPLIN-UFSM/rankings/files/13672701/lista_universidades_brasileiras.xlsx)

**Comment by flrivas** [comment]
Atualização da lista filtrada das universidades que estão presentes nos rankings com foco nas universidades brasileiras.
O que foi feito:

- criação da coluna indicando a qual estado cada instituição pertence;
- somatório do número de instituições por estado.
 
[lista_universidades_brasileiras.xlsx](https://github.com/COPLIN-UFSM/rankings/files/13728635/lista_universidades_brasileiras.xlsx)

**Comment by flrivas** [comment]
[lista_universidades_brasileiras)_BACKUP.xlsx](https://github.com/COPLIN-UFSM/rankings/files/13874611/lista_universidades_brasileiras._BACKUP.xlsx)
Linhas em vermelho significa que não foram encontrados valores correspondentes em R_UNIVERSIDADES ou MICRODADOS_IES.

**Comment by henryzord** [comment]
Vou usar os dados da Planilha 3 do documento do comentário acima.

A relação entre as universidades em `R_UNIVERSIDADES` e o `COD_IES` (como por exemplo da tabela `MICRODADOS_IES`) está na tabela `R_UNIVERSIDADES_PARA_IES`.
