### ISSUE TITLE
Medidas e tabelas criadas

### ISSUE THREAD

**Issue by NathaleCK** [COPLIN-UFSM/rankings#9]
**Tabela dCalendario**

```
dCalendario = 
ADDCOLUMNS(
    CALENDAR(
        MIN(fValoresPilares[Date]),
        MAX(fValoresPilares[Date])
    ),
    "Ano", YEAR([Date])
    )
```

**Comment by diego-brenner-reis** [comment]
Nota Geral UFSM = CALCULATE([Nota Dimensão UFSM], ALL(dRanking[NOME_PILAR_PORTUGUES]))

Nota Dimensão Anterior UFSM = CALCULATE([Nota Dimensão UFSM], DATEADD(dCalendario[Date],-1, YEAR))

Nota Geral Anterior UFSM = CALCULATE([Nota Geral UFSM], DATEADD(dCalendario[Date],-1, YEAR))

Participação na Nota Geral % = DIVIDE([Nota Dimensão UFSM], [Nota Geral UFSM])

Posição Geral no Ranking = RANKX(ALL(dUniversidade[NOME_UNIVERSIDADE_PORTUGUES]), [Nota Dimensão UFSM])

Posição no Ranking BR = RANKX(
    FILTER(ALL(dUniversidade), dUniversidade[NOME_PAIS_PORTUGUES] = "Brasil"),
    [Nota Dimensão UFSM])

Qt Universidades = 
    CALCULATE(
        DISTINCTCOUNT(fValoresPilares[ID_UNIVERSIDADE]),
        ALL(dUniversidade))

QT Universidades Anterior = CALCULATE([Qt Universidades], DATEADD(dCalendario[Date],-1, YEAR))

Qt Universidades BR = 
    CALCULATE(
        DISTINCTCOUNT(fValoresPilares[ID_UNIVERSIDADE]),
        ALL(dUniversidade),
        dUniversidade[NOME_PAIS_PORTUGUES]="Brasil")

QT Universidades BR Anterior = CALCULATE([Qt Universidades BR], DATEADD(dCalendario[Date],-1, YEAR))

Variação Dimensão % = DIVIDE([Nota Dimensão UFSM], [Nota Dimensão Anterior UFSM])-1

Variação Nota Geral % = DIVIDE([Nota Geral UFSM], [Nota Geral Anterior UFSM])-1

Variação Qt % = DIVIDE([Qt Universidades], [QT Universidades Anterior])-1

Variação Qt BR % = DIVIDE([Qt Universidades BR], [QT Universidades BR Anterior])-1

**Comment by henryzord** [comment]
duplicado: juntar com https://github.com/COPLIN-UFSM/rankings/issues/6

**Comment by NathaleCK** [comment]
> duplicado: juntar com #6

Uma coisa é uma coisa, outra coisa é outra coisa. (não sei juntar)

**Comment by henryzord** [comment]
só dá pra juntar na mão. então teria que copiar o texto de lá e colar
aqui... 😬

Em sex., 15 de dez. de 2023 às 13:16, NathaleCK ***@***.***>
escreveu:

**Comment by NathaleCK** [comment]
Relatório pronto.
